# Generated by Django 5.0.6 on 2024-06-04 06:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duty', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duty',
            name='people',
        ),
        migrations.AddField(
            model_name='duty',
            name='duty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Дежурный'),
        ),
        migrations.AlterField(
            model_name='duty',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата дежурства'),
        ),
        migrations.AlterModelTable(
            name='duty',
            table='duties',
        ),
        migrations.DeleteModel(
            name='People',
        ),
    ]
