# Generated by Django 5.0.6 on 2024-06-16 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('duty', '0003_alter_duty_duty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='duty',
            old_name='duty',
            new_name='attendant',
        ),
    ]
