# Generated by Django 5.0.6 on 2024-06-03 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_alter_user_options_alter_user_password_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='role',
            table='auth_role',
        ),
    ]
