# Generated by Django 5.0.6 on 2024-06-03 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0005_token'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='token',
            table='auth_token',
        ),
    ]
