# Generated by Django 5.0.6 on 2024-06-13 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0006_alter_token_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='group',
            field=models.CharField(default=None, max_length=10, null=True, verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='authorization.role', verbose_name='Роль'),
        ),
    ]
